jpeg("/Users/dronemist/Desktop/plot/ConExp1.jpg", width = 500, height = 500)
plot( fitdist(df2, "exp") )
dev.off()
jpeg("/Users/dronemist/Desktop/plot/ConLog1.jpg", width = 500, height = 500)
plot( fitdist(df2, "lnorm") )
dev.off()
jpeg("/Users/dronemist/Desktop/plot/ConNor1.jpg", width = 500, height = 500)
plot( fitdist(df2, "norm") )
dev.off()


jpeg("/Users/dronemist/Desktop/plot/ConExp2.jpg", width = 500, height = 500)
plot( fitdist(df2, "exp") )
dev.off()
jpeg("/Users/dronemist/Desktop/plot/ConLog2.jpg", width = 500, height = 500)
plot( fitdist(df2, "lnorm") )
dev.off()
jpeg("/Users/dronemist/Desktop/plot/ConNor2.jpg", width = 500, height = 500)
plot( fitdist(df2, "norm") )
dev.off()

jpeg("/Users/dronemist/Desktop/plot/ConExp3.jpg", width = 500, height = 500)
plot( fitdist(df2, "exp") )
dev.off()
jpeg("/Users/dronemist/Desktop/plot/ConLog3.jpg", width = 500, height = 500)
plot( fitdist(df2, "lnorm") )
dev.off()
jpeg("/Users/dronemist/Desktop/plot/ConNor3.jpg", width = 500, height = 500)
plot( fitdist(df2, "norm") )
dev.off()

jpeg("/Users/dronemist/Desktop/plot/PackExp1.jpg", width = 500, height = 500)
plot( fitdist(df2, "exp") )
dev.off()
jpeg("/Users/dronemist/Desktop/plot/PackLog1.jpg", width = 500, height = 500)
plot( fitdist(df2, "lnorm") )
dev.off()
jpeg("/Users/dronemist/Desktop/plot/PackNor1.jpg", width = 500, height = 500)
plot( fitdist(df2, "norm") )
dev.off()

jpeg("/Users/dronemist/Desktop/plot/PackExp2.jpg", width = 500, height = 500)
plot( fitdist(df2, "exp") )
dev.off()
jpeg("/Users/dronemist/Desktop/plot/PackLog2.jpg", width = 500, height = 500)
plot( fitdist(df2, "lnorm") )
dev.off()
jpeg("/Users/dronemist/Desktop/plot/PackNor2.jpg", width = 500, height = 500)
plot( fitdist(df2, "norm") )
dev.off()

jpeg("/Users/dronemist/Desktop/plot/PackExp3.jpg", width = 500, height = 500)
plot( fitdist(df2, "exp") )
dev.off()
jpeg("/Users/dronemist/Desktop/plot/PackLog3.jpg", width = 500, height = 500)
plot( fitdist(df2, "lnorm") )
dev.off()
jpeg("/Users/dronemist/Desktop/plot/PackNor3.jpg", width = 500, height = 500)
plot( fitdist(df2, "norm") )
dev.off()

fe <-fitdist(df2, "exp")
fe

fe <-fitdist(df2, "norm")
fe

fe <-fitdist(df2, "lnorm")
fe